ChatNet/Controllers/AuthController.cs
using ChatNet.Database;
using ChatNet.Domain.Entity;
using ChatNet.Services.Helpers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ChatNet.Controllers;

public class AuthController : Controller
{
    private readonly AppDbContext _context;

    public AuthController(AppDbContext context)
    {
        _context = context;
    }

    [HttpGet]
    public IActionResult Register()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Register(string username, string password, string email)
    {
        if (string.IsNullOrEmpty(username) || string.IsNullOrEmpty(password) || string.IsNullOrEmpty(email))
        {
            ModelState.AddModelError("", "All fields are required.");
            return View();
        }

        var existingUser = _context.Users.FirstOrDefault(u => u.Email == email);
        if (existingUser != null)
        {
            ModelState.AddModelError("", "A user with this email already exists.");
            return View();
        }

        var newUser = new User(username, password, email);
        _context.Users.Add(newUser);
        await _context.SaveChangesAsync();
        return RedirectToAction("Login");
    }

    [HttpGet]
    public IActionResult Login()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Login(string email, string password)
    {
        if (string.IsNullOrEmpty(email) || string.IsNullOrEmpty(password))
        {
            ModelState.AddModelError("", "Both fields are required.");
            return View();
        }

        var user = await _context.Users.FirstOrDefaultAsync(u => u.Email == email);

        if (user == null)
        {
            ModelState.AddModelError("", "No user found");
            return View();
        }

        var result = PasswordHelper.VerifyPassword(password, user.Password);

        if (!result)
        {
            ModelState.AddModelError("", "Bad password");
            return View();
        }

        HttpContext.Session.SetString("UserName", user.Name);
        HttpContext.Session.SetInt32("id", user.Id);
        return RedirectToAction("Index", "Home");
    }

    public IActionResult Logout()
    {
        HttpContext.Session.Clear();
        return RedirectToAction("Index", "Home");
    }
}

ChatNet/Controllers/ChatController.cs
using ChatNet.Domain.Entity;
using ChatNet.Models;
using ChatNet.Services.Interfaces;
using ChatNet.SignalR;
using Microsoft.AspNetCore.Mvc;

namespace ChatNet.Controllers;
public class ChatController : Controller
{
    private readonly IUserService _userService;
    private readonly IChatService _chatService;
    private readonly OnlineUsersService _onlineUsersService;

    public ChatController(IUserService userService, IChatService chatService, OnlineUsersService onlineUsersService)
    {
        _userService = userService;
        _onlineUsersService = onlineUsersService;
        _chatService = chatService;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var model = await LoadData();
        return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> LoadChat(int userId)
    {
        var model = await LoadData();
        model.CurrentChat = await _userService.GetUser(userId);
        model.Messages = await _chatService.GetMessagesForChat(model.UserId, model.CurrentChat.Id);
        return PartialView("ChatRoomPartial", model);
    }

    [HttpPost]
    public async Task SaveMessage(int reciverId, string message)
    {
        var id = (int)HttpContext.Session.GetInt32("id");

        var user = await _userService.GetUser(id);
        var reciver = await _userService.GetUser(reciverId);

        var result = new Message(user, reciver, message);
        await _chatService.AddMessage(result);
    }

    public async Task<ChatViewModel> LoadData()
    {
        var id = (int)HttpContext.Session.GetInt32("id");

        var user = await _userService.GetUser(id);
        var onlineUsers = _onlineUsersService.GetOnlineUsers();

        return new ChatViewModel(user.Friends, onlineUsers.ToList(), user.Name, id);
    }
}

ChatNet/Controllers/FriendsController.cs
using ChatNet.Domain.Entity;
using ChatNet.Models;
using ChatNet.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace ChatNet.Controllers;

public class FriendsController : Controller
{
    private readonly IUserService _userService;
    private readonly IChatService _chatService;

    public FriendsController(IUserService userService, IChatService chatService)
    {
        _userService = userService;
        _chatService = chatService;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var id = (int)HttpContext.Session.GetInt32("id");

        var availableFriends = await _userService.GetAviableFriends();
        var friendsIds = await _userService.GetInvitedFriendsByUserId(id);
        var user = await _userService.GetUser(id);

        var data = new SearchFriendViewModel
        {
            AviableFriends = new Dictionary<User, bool>(),
            UserInvites = await _userService.GetUsersWhoInvited(id),
            Friends = user.Friends
        };

        foreach (var friend in availableFriends.ToList())
        {

            if (data.UserInvites.Any(u => u.Id == friend.Id))
            {
                availableFriends.Remove(friend);
                continue;
            }

            bool isFriend = friendsIds.Contains(friend.Id);

            data.AviableFriends[friend] = isFriend;
        }

        return View(data);
    }

    [HttpPost]
    public async Task<IActionResult> AddInvite(int invitedId, bool isUserInvite)
    {
        var id = (int)HttpContext.Session.GetInt32("id");
        var invitedUser = await _userService.GetUser(invitedId);

        if (isUserInvite)
        {
            await _userService.AddInvite(id, invitedId);
        }
        else
        {
            await _userService.AddFriend(id, invitedId);
        }

        return RedirectToAction("Index");
    }

    [HttpPost]
    public async Task<IActionResult> RemoveInvite(int invitedId, bool isUserInvite)
    {
        var id = (int)HttpContext.Session.GetInt32("id");
        var invitedUser = await _userService.GetUser(invitedId);

        if (isUserInvite)
        {
            await _userService.RemoveInvite(id, invitedId);
        }
        else
        {
            await _userService.RemoveInvite(invitedId, id);
        }
        return RedirectToAction("Index");
    }

    [HttpPost]
    public async Task<IActionResult> RemoveFriend(int friendId)
    {
        var id = (int)HttpContext.Session.GetInt32("id");
        await _userService.RemoveFriend(id, friendId);
        await _chatService.RemoveMessagesFromChat(id, friendId);

        return RedirectToAction("Index");
    }
}

ChatNet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChatNet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ChatNet.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/microsoft/signalr/dist/browser/signalr.js"></script>

</head>
<body style="background-color: rgb(210, 210, 210)">
    <header style="background-color: white">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ChatNet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (Context.Session.GetString("UserName") != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Friends" asp-action="Index">Friends & invites</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Chat" asp-action="Index">Chat</a>
                            </li>
                            <li class="nav-item">
                                <form asp-controller="Auth" asp-action="Logout" method="post">
                                    <button class="nav-link btn btn-link text-dark">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color: white">
        <div class="container">
            &copy; 2025 - ChatNet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <div aria-live="polite" aria-atomic="true" class="position-relative">
        <div id="toastContainer" class="toast-container position-fixed top-0 end-0 p-3"></div>
    </div>
</body>
</html>

<script>
    const connection = new signalR.HubConnectionBuilder()
        .withUrl("/notificationHub")
        .build();

    connection.start()
        .then(() => {
            console.log("Połączono z NotificationHub");
        })
        .catch(err => {
            console.error("Błąd połączenia z SignalR:", err);
        });

    connection.on("ReceiveNotification", function (message) {
        //console.log("Otrzymano powiadomienie: ", message);
        showToast(message);
        setTimeout(() => {
        }, 5000);
    });
</script>

<script>
    function showToast(message) {
        const toastContainer = document.getElementById("toastContainer");

        const toastHTML = `
            <div class="toast align-items-center text-bg-primary border-0 show" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="d-flex">
                    <div class="toast-body">
                        ${message}
                    </div>
                    <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
            </div>`;

        const toastElement = document.createElement("div");
        toastElement.innerHTML = toastHTML;
        toastContainer.appendChild(toastElement);

        const toast = new bootstrap.Toast(toastElement.querySelector(".toast"));
        toast.show();

        setTimeout(() => {
            toast.dispose();
            toastElement.remove();
        }, 5000);
    }
</script>